### ISSUE TITLE
Error missing body when adding attachments

### ISSUE THREAD

**Issue by vddgil** [resendlabs/resend-ruby#29]
Hello,

We are using the gem with rails and action mailer, as soon as we add an attachment to an email, we end up with the following error from the API: "Resend::Error::InvalidRequestError: Missing `html` or `text` field".
Every other emails (without attachment) are workink fine.

All the emails were perfectly working before with Mailjet :(

We are a paying customer and it's a production application, please advise asap.

Thanks a lot

**Comment by vddgil** [comment]
Found out that it was fixed on master, I updated my Gemfile to use the master, it's now working fine.

**Comment by drish** [comment]
hey @vddgil I have just released v0.4.0 that should have that fix in, so you don't have to keep pointing to main.
thanks for your patience there !
